--DATABASE CREATION 
use master 
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'ICEDB')
DROP DATABASE ICEDB
CREATE DATABASE ICEDB
use ICEDB

--TABLE CREATION SECTION 
CREATE TABLE Student (
StudentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
STNumber VARCHAR(10) UNIQUE NOT NULL,
FullName VARCHAR(MAX) NOT NULL
);

CREATE TABLE Module(
ModuleID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
Qualification VARCHAR(50) NOT NULL,
Code VARCHAR(80) NOT NULL
);


--TABLE INSERTION SECTION
INSERT INTO Student(STNumber, FullName)
VALUES ('ST10456656', 'Senamiso Ndlovu'),
('ST46789','Jane Doe')

INSERT INTO Module
VALUES ('BCAD','CLDV6211'),
('HMAW','MAST5112')


--TABLE MANIPULATION SECTION
SELECT * FROM Student
SELECT * FROM Module


--STORED PROCEDURE SECTION



